version: '3.8'
services:
  flask_app:
    build: ./flask_app
    ports:
      - "5001:5001"
    volumes:
      - ./flask_app:/app

  fastapi_app:
    build: ./fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi_app:/app

  streamlit_app:
    build: ./streamlit_app
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_app:/app
